vadetis/urls.py
# from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.defaults import page_not_found
from vadetisweb.urls import apipatterns

schema_view = get_schema_view(
    openapi.Info(
        title="Vadetis API",
        default_version='v1',
        description="API for Vadetis",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="lisaexascale@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=(permissions.IsAdminUser,),
    patterns=apipatterns
)

urlpatterns = [
    path('', include('vadetisweb.urls', namespace='vadetisweb')),
    path('accounts/password/set/', page_not_found, {'exception': Exception()}),
    path('accounts/password/change/', page_not_found, {'exception': Exception()}),
    path('accounts/social/connections/', page_not_found, {'exception': Exception()}),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),

    re_path('swagger(?P<format>\.json|\.yaml)', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

vadetisweb/urls.py
from django.urls import path, include
from rest_framework import routers

from vadetisweb import views

app_name = 'vadetisweb'

"""
    format patterns: provide either rendered view or json, depending if ajax is used, 
    we do not use format_suffix_patterns as we use query parameter (e.g. ?format=json)
    
    api paths: provide data as json
"""

router = routers.DefaultRouter()
router.register(r'account/datasets', views.AccountDatasetDataTableViewSet, basename='account_datasets_datatable')
router.register(r'account/training-datasets', views.AccountTrainingDatasetDataTableViewSet, basename='account_training_datasets_datatable')
router.register(r'display/datasets/synthetic', views.DisplaySyntheticDatasetDataTableViewSet, basename='display_synthetic_datasets_datatable')
router.register(r'display/datasets/real-world', views.DisplayRealWorldDatasetDataTableViewSet, basename='display_real_world_datasets_datatable')
router.register(r'display/training-datasets', views.DisplayTrainingDatasetDataTableViewSet, basename='display_training_datasets_datatable')
router.register(r'detection/datasets/synthetic', views.DetectionSyntheticDatasetDataTableViewSet, basename='detection_synthetic_datasets_datatable')
router.register(r'detection/datasets/real-world', views.DetectionRealWorldDatasetDataTableViewSet, basename='detection_real_world_datasets_datatable')
router.register(r'recommendation/datasets/synthetic', views.RecommendationSyntheticDatasetDataTableViewSet, basename='recommendation_synthetic_datasets_datatable')
router.register(r'recommendation/datasets/real-world', views.RecommendationRealWorldDatasetDataTableViewSet, basename='recommendation_real_world_datasets_datatable')

apipatterns = [
    path('api/', include((router.urls))),
    path('api/detection/<int:dataset_id>/', views.DetectionAlgorithmSelectionView.as_view(), name='detection_algorithm_selection'),
    path('api/detection/<int:dataset_id>/lisa/pearson', views.DetectionLisaPearson.as_view(), name='detection_lisa_person'),
    path('api/detection/<int:dataset_id>/lisa/dtw-pearson', views.DetectionLisaDtwPearson.as_view(), name='detection_lisa_dtw_person'),
    path('api/detection/<int:dataset_id>/lisa/geo', views.DetectionLisaGeoDistance.as_view(), name='detection_lisa_geo'),
    path('api/detection/<int:dataset_id>/rpca/mestimator', views.DetectionRPCAMEstimatorLoss.as_view(), name='detection_rpca_mestimator'),
    path('api/detection/<int:dataset_id>/histogram', views.DetectionHistogram.as_view(), name='detection_histogram'),
    path('api/detection/<int:dataset_id>/cluster', views.DetectionCluster.as_view(), name='detection_cluster'),
    path('api/detection/<int:dataset_id>/svm', views.DetectionSVM.as_view(), name='detection_svm'),
    path('api/detection/<int:dataset_id>/isolationforest', views.DetectionIsolationForest.as_view(), name='detection_isolation_forest'),

    path('api/injection/<int:dataset_id>/', views.InjectionView.as_view(), name='injection_anomaly'),

    path('api/recommendation/<int:dataset_id>/', views.RecommendationView.as_view(), name='recommendation_scores'),

    path('api/dataset/<int:dataset_id>/', views.DatasetJson.as_view(), name='dataset_json'),
    path('api/dataset/<int:dataset_id>/update/', views.AccountDatasetUpdate.as_view(), name='account_dataset_update'),
    path('api/dataset/<int:dataset_id>/delete/', views.AccountDatasetDelete.as_view(), name='account_dataset_delete'),
    path('api/training-dataset/<int:dataset_id>/update/', views.AccountTrainingDatasetUpdate.as_view(), name='account_training_dataset_update'),
    path('api/training-dataset/<int:dataset_id>/delete/', views.AccountTrainingDatasetDelete.as_view(), name='account_training_dataset_delete'),

    path('api/dataset/search/', views.DatasetSearchView.as_view(), name='dataset_search'),
    path('api/dataset/download/', views.DatasetFileDownload.as_view(), name='dataset_download_file'),

    path('api/portlet/image/', views.ImagePortlet.as_view(), name='image_portlet'),
    path('api/portlet/score/', views.ScorePortlet.as_view(), name='score_portlet'),
    path('api/portlet/recommendation/', views.RecommendationPortlet.as_view(), name='recommendation_portlet'),
    path('api/portlet/recommendation-summary/', views.RecommendationSummaryPortlet.as_view(), name='recommendation_summary_portlet'),
    path('api/portlet/threshold/', views.ThresholdFormPortlet.as_view(), name='threshold_portlet'),
    path('api/portlet/injection/<int:dataset_id>/', views.InjectionFormPortlet.as_view(), name='injection_form_portlet'),

    path('api/threshold-update', views.DatasetThresholdUpdateJson.as_view(), name='threshold_update_json'),
    path('api/image/cnf/', views.CnfImage.as_view(), name='cnf_image'),
    path('api/image/thresholds-scores/', views.ThresholdsScoresImage.as_view(), name='thresholds_scores_image'),

    path('api/locations/<int:dataset_id>/', views.DatasetLocationsJson.as_view(), name='dataset_locations'),
]

urlpatterns = apipatterns + [

    path('account/datasets/upload/', views.AccountUploadDataset.as_view(), name='account_datasets_upload'),
    path('account/training-datasets/upload/', views.AccountUploadTrainingDataset.as_view(), name='account_training_datasets_upload'),

    path('display/real-world/', views.DisplayRealWorldDatasets.as_view(), name='display_real_world_datasets'),
    path('display/real-world/<int:dataset_id>/', views.DisplayRealWorldDataset.as_view(), name='display_real_world_dataset'),
    path('display/real-world/<int:dataset_id>/<int:training_dataset_id>/', views.DisplayRealWorldTrainingDataset.as_view(), name='display_real_world_training_dataset'),
    path('display/synthetic/', views.DisplaySyntheticDatasets.as_view(), name='display_synthetic_datasets'),
    path('display/synthetic/<int:dataset_id>/', views.DisplaySyntheticDataset.as_view(), name='display_synthetic_dataset'),
    path('display/synthetic/<int:dataset_id>/<int:training_dataset_id>/', views.DisplaySyntheticTrainingDataset.as_view(), name='display_synthetic_training_dataset'),

    path('detection/real-world/', views.DetectionRealWorldDatasets.as_view(), name='detection_real_world_datasets'),
    path('detection/real-world/<int:dataset_id>/', views.DetectionRealWorldDataset.as_view(), name='detection_real_world_dataset'),
    path('detection/synthetic/', views.DetectionSyntheticDatasets.as_view(), name='detection_synthetic_datasets'),
    path('detection/synthetic/<int:dataset_id>/', views.DetectionSyntheticDataset.as_view(), name='detection_synthetic_dataset'),

    path('recommendation/real-world/', views.RecommendationRealWorldDatasets.as_view(), name='recommendation_real_world_datasets'),
    path('recommendation/real-world/<int:dataset_id>/', views.RecommendationRealWorldDataset.as_view(), name='recommendation_real_world_dataset'),
    path('recommendation/synthetic/', views.RecommendationSyntheticDatasets.as_view(), name='recommendation_synthetic_datasets'),
    path('recommendation/synthetic/<int:dataset_id>/', views.RecommendationSyntheticDataset.as_view(), name='recommendation_synthetic_dataset'),

    path('account/application-setting/', views.ApplicationSetting.as_view(), name='application_setting'),
    path('account/datasets/', views.account_datasets, name='account_datasets'),
    path('account/datasets/<int:dataset_id>/edit/', views.AccountDatasetEdit.as_view(), name='account_dataset_edit'),
    path('account/training-datasets/<int:dataset_id>/edit/', views.AccountTrainingDatasetEdit.as_view(), name='account_training_dataset_edit'),
    path('account/training-datasets/', views.account_training_datasets, name='account_training_datasets'),
    path('account/user/update', views.AccountUserUpdate.as_view(), name='account_user_update'),
    path('account/pwd/update', views.AccountPasswordUpdate.as_view(), name='account_pwd_update'),
    path('account/delete', views.AccountDelete.as_view(), name='account_delete'),
    path('account/', views.account, name='account'),


    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

vadetisweb/models/user_models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models

from vadetisweb.parameters import *


class UserSetting(models.Model):
    """
    The user settings for the application.
    """

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    color_outliers = models.CharField('Color outliers', max_length=7, null=False, default=DEFAULT_COLOR_OUTLIERS,
                                      help_text='Default: #C30000, the RGB color used to mark outliers',
                                      validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    color_true_positive = models.CharField('Color for True Positives', max_length=7, null=False, default=DEFAULT_COLOR_TRUE_POSITIVES,
                                           help_text='Default: #008800, the RGB color used to mark true positives',
                                           validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    color_false_positive = models.CharField('Color for False Positives', max_length=7, null=False, default=DEFAULT_COLOR_FALSE_POSITIVES,
                                            help_text='Default: #FF0000, the RGB color used to mark false positives',
                                            validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    color_false_negative = models.CharField('Color for False Negatives', max_length=7, null=False, default=DEFAULT_COLOR_FALSE_NEGATIVES,
                                            help_text='Default: #0000FF, the RGB color used to mark false negatives',
                                            validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    def __str__(self):
        if self.user is not None:
            return self.user.username
        else:
            return 'Settings'

vadetisweb/forms/account_forms.py
from allauth.account import app_settings
from allauth.account.forms import get_adapter as get_account_adapter, SetPasswordForm, filter_users_by_email
from allauth.account.models import EmailAddress
from django.forms import ModelForm, ValidationError

from vadetisweb.models import User


#########################################################
# Account Forms
#########################################################

class AccountUserForm(ModelForm):
    """
    The form for the user basic config
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(AccountUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class' : 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        setattr(self, '__original_email', self.instance.email)

    def valid_email(self):
        value = self.instance.email
        value = get_account_adapter().clean_email(value)
        errors = {
            "different_account": "This e-mail address is already associated with another account.",
        }
        users = filter_users_by_email(value)
        on_diff_account = [u for u in users if u.pk != self.user.pk]

        if on_diff_account and app_settings.UNIQUE_EMAIL:
            raise ValidationError(errors["different_account"])
        return value

    def save(self, commit=True):
        instance = super(AccountUserForm, self).save(commit=False)

        email_address = EmailAddress.objects.get(email__iexact=getattr(self, '__original_email'), user=self.instance)
        if email_address is not None:
            email_address.email = self.cleaned_data['email']
            email_address.save()
        else:
            raise ValidationError('Something went wrong, could not set email address')
        if commit:
            instance.save()
        return instance


class AccountSetPasswordForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(AccountSetPasswordForm, self).__init__(*args, **kwargs)
        for field in ('password1', 'password2'):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def save(self):
        # Ensure you call the parent classes save
        # .save() does not return anything
        super(AccountSetPasswordForm, self).save()

vadetisweb/views.py
from django.shortcuts import render


def index(request):

    return render(request, 'vadetisweb/index.html',)

vadetisweb/views/base_views.py
from django.shortcuts import render

def index(request):
    return render(request, 'vadetisweb/index.html',)

def about(request):
    return render(request, 'vadetisweb/about.html')

def faq(request):
    return render(request, 'vadetisweb/faq.html')

vadetisweb/templates/vadetisweb/suggestion/synthetic/dataset.html
{% extends 'vadetisweb/suggestion/synthetic/datasets.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% load vadetistags %}
{% load rest_framework %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb dataset.title "vadetisweb:suggestion_synthetic_dataset" dataset_id=dataset.id %}
{% endblock %}

{% block css %}
    {{ block.super }}
    {% include 'vadetisweb/parts/includes/highcharts_css.html' %}
{% endblock %}

{% block head_js %}
    {{ block.super }}
    <script type="text/javascript">
        const cnf_url = "{% get_host_url request=request %}{% url 'vadetisweb:cnf_image' %}";
        const plot_url = "{% get_host_url request=request %}{% url 'vadetisweb:thresholds_scores_image' %}";
    </script>
{% endblock %}

{% block page_title %}
    <h3 class="kt-subheader__title">Suggestion</h3>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">{{ dataset.title }}</h3>
                    </div>
                    <div class="kt-portlet__head-toolbar">
                        <div id="highcharts_head_actions" class="kt-portlet__head-actions">
                            <a id="clear_chart_btn" href="#" class="btn btn-outline-brand btn-bold btn-sm">Clear</a>
                            <div class="dropdown dropdown-inline">
                                <a href="#" class="btn btn-outline-brand btn-icon btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="mdi mdi-18px mdi-dots-horizontal"></i>
                                </a>
                                {% url 'vadetisweb:display_synthetic_dataset' dataset_id=dataset.id as display_link %}
                                {% url 'vadetisweb:detection_synthetic_dataset' dataset_id=dataset.id as detection_link %}
                                {% include 'vadetisweb/parts/misc/highcharts_column_dropdown.html' with display_link=display_link detection_link=detection_link %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__body kt-portlet__body--fit">
                    <!--begin: Highcharts -->
                    <div id=highcharts_container></div>
                    <!--end: Highcharts -->
                </div>
            </div>
            <!--begin: Inner Row -->
            <div id="suggestion_portlets" class="row"></div>
            <!--end: Inner Row -->
        </div>
        <div id="form_portlets" class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
            <div class="kt-portlet" data-ktportlet="true">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">Load Suggestion</h3>
                    </div>
                    <div class="kt-portlet__head-toolbar">
                        <div class="kt-portlet__head-group">
                            <a href="#" data-ktportlet-tool="toggle" class="btn btn-sm btn-icon btn-default btn-icon-md"><i class="mdi mdi-chevron-down mdi-18px"></i></a>
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__body kt-portlet__body--fit">
                    {% url 'vadetisweb:suggestion_scores' dataset_id=dataset.id  as suggestion_url %}
                    {% include 'vadetisweb/parts/forms/serializer_variable_form.html' with formid="suggestion_form" url=suggestion_url form_serializer=suggestion_serializer submit_label="Compute" %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block additional_bottom_js %}
    <!-- page extensions -->
    <script src="{% static 'js/lib/binarytransport/jquery.binarytransport.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/lib/highcharts/highstock.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/lib/highcharts/modules/no-data-to-display.js' %}"></script>
    <script src="{% static 'js/custom/highcharts.utils.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/custom/highcharts.actions.init.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/custom/highcharts.column.view.init.js' %}" type="text/javascript"></script>
    <!-- page init -->
    <script src="{% static 'js/page/suggestion/form.init.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/page/suggestion/page.init.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            DatasetSuggestionForm.init("suggestion_form", "{% url 'vadetisweb:suggestion_portlet' %}?format=html", "{% url 'vadetisweb:suggestion_recommendation_portlet' %}?format=html");
            DatasetSuggestionPage.init("clear_chart_btn");
        });
    </script>
{% endblock %}

vadetisweb/templates/vadetisweb/suggestion/synthetic/datasets.html
{% extends 'vadetisweb/base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% load rest_framework %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Synthetic Datasets" "vadetisweb:suggestion_synthetic_datasets" %}
{% endblock %}

{% block css %}
    {{ block.super }}
    <link href="{% static 'css/lib/datatables/datatables.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block page_title %}
    <h3 class="kt-subheader__title">Suggestion</h3>
{% endblock %}

{% block content %}
    <div class="kt-portlet">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="mdi mdi-chart-timeline-variant mdi-24px kt-font-brand"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Table of Synthetic Datasets
                </h3>
            </div>
        </div>
        <div class="kt-portlet__body">
            <div class="kt-portlet shadow-none kt-portlet--fit kt-portlet--collapsed mb-0" data-ktportlet="true">
                <div class="kt-portlet__head border-bottom-0">
                    <div class="kt-portlet__head-toolbar">
                        <div class="kt-portlet__head-group">
                            <span class="font-weight-bold">Search Table</span> <a href="#" data-ktportlet-tool="toggle" class="btn btn-sm btn-icon btn-default btn-icon-md"><i class="mdi mdi-chevron-down mdi-18px"></i></a>
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__body mt-3">
                    {% include 'vadetisweb/parts/forms/serializer_datatables_search_form.html' with serializer=search_serializer %}
                </div>
            </div>
            <!--begin: Datatable -->
            <table id="table_synthetic_datasets" class="table table-bordered table-hover table-checkable"></table>
            <!--end: Datatable -->
        </div>
    </div>
{% endblock %}

{% block additional_bottom_js %}
    {{ block.super }}
    <script src="{% static 'js/lib/datatables/datatables.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/custom/datatables.init.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            VadetisDatatables.init("table_synthetic_datasets", "{% url 'vadetisweb:suggestion_synthetic_datasets_datatable-list' %}?format=datatables");
        });
    </script>
{% endblock %}