vadetis/urls.py
# from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.defaults import page_not_found
from vadetisweb.urls import apipatterns

schema_view = get_schema_view(
    openapi.Info(
        title="Vadetis API",
        default_version='v1',
        description="API for Vadetis",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="lisaexascale@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=(permissions.IsAdminUser,),
    patterns=apipatterns
)

urlpatterns = [
    path('', include('vadetisweb.urls', namespace='vadetisweb')),
    path('accounts/password/set/', page_not_found, {'exception': Exception()}),
    path('accounts/password/change/', page_not_found, {'exception': Exception()}),
    path('accounts/social/connections/', page_not_found, {'exception': Exception()}),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),

    re_path('swagger(?P<format>\.json|\.yaml)', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

vadetisweb/urls.py
from django.urls import path, include
from rest_framework import routers

from vadetisweb import views

app_name = 'vadetisweb'

"""
    format patterns: provide either rendered view or json, depending if ajax is used, 
    we do not use format_suffix_patterns as we use query parameter (e.g. ?format=json)
    
    api paths: provide data as json
"""

router = routers.DefaultRouter()
router.register(r'account/datasets', views.AccountDatasetDataTableViewSet, basename='account_datasets_datatable')
router.register(r'account/training-datasets', views.AccountTrainingDatasetDataTableViewSet, basename='account_training_datasets_datatable')
router.register(r'display/datasets/synthetic', views.DisplaySyntheticDatasetDataTableViewSet, basename='display_synthetic_datasets_datatable')
router.register(r'display/datasets/real-world', views.DisplayRealWorldDatasetDataTableViewSet, basename='display_real_world_datasets_datatable')
router.register(r'display/training-datasets', views.DisplayTrainingDatasetDataTableViewSet, basename='display_training_datasets_datatable')
router.register(r'detection/datasets/synthetic', views.DetectionSyntheticDatasetDataTableViewSet, basename='detection_synthetic_datasets_datatable')
router.register(r'detection/datasets/real-world', views.DetectionRealWorldDatasetDataTableViewSet, basename='detection_real_world_datasets_datatable')
router.register(r'recommendation/datasets/synthetic', views.RecommendationSyntheticDatasetDataTableViewSet, basename='recommendation_synthetic_datasets_datatable')
router.register(r'recommendation/datasets/real-world', views.RecommendationRealWorldDatasetDataTableViewSet, basename='recommendation_real_world_datasets_datatable')

apipatterns = [
    path('api/', include((router.urls))),
    path('api/detection/<int:dataset_id>/', views.DetectionAlgorithmSelectionView.as_view(), name='detection_algorithm_selection'),
    path('api/detection/<int:dataset_id>/lisa/pearson', views.DetectionLisaPearson.as_view(), name='detection_lisa_person'),
    path('api/detection/<int:dataset_id>/lisa/dtw-pearson', views.DetectionLisaDtwPearson.as_view(), name='detection_lisa_dtw_person'),
    path('api/detection/<int:dataset_id>/lisa/geo', views.DetectionLisaGeoDistance.as_view(), name='detection_lisa_geo'),
    path('api/detection/<int:dataset_id>/rpca/mestimator', views.DetectionRPCAMEstimatorLoss.as_view(), name='detection_rpca_mestimator'),
    path('api/detection/<int:dataset_id>/histogram', views.DetectionHistogram.as_view(), name='detection_histogram'),
    path('api/detection/<int:dataset_id>/cluster', views.DetectionCluster.as_view(), name='detection_cluster'),
    path('api/detection/<int:dataset_id>/svm', views.DetectionSVM.as_view(), name='detection_svm'),
    path('api/detection/<int:dataset_id>/isolationforest', views.DetectionIsolationForest.as_view(), name='detection_isolation_forest'),

    path('api/injection/<int:dataset_id>/', views.InjectionView.as_view(), name='injection_anomaly'),

    path('api/recommendation/<int:dataset_id>/', views.RecommendationView.as_view(), name='recommendation_scores'),

    path('api/dataset/<int:dataset_id>/', views.DatasetJson.as_view(), name='dataset_json'),
    path('api/dataset/<int:dataset_id>/update/', views.AccountDatasetUpdate.as_view(), name='account_dataset_update'),
    path('api/dataset/<int:dataset_id>/delete/', views.AccountDatasetDelete.as_view(), name='account_dataset_delete'),
    path('api/training-dataset/<int:dataset_id>/update/', views.AccountTrainingDatasetUpdate.as_view(), name='account_training_dataset_update'),
    path('api/training-dataset/<int:dataset_id>/delete/', views.AccountTrainingDatasetDelete.as_view(), name='account_training_dataset_delete'),

    path('api/dataset/search/', views.DatasetSearchView.as_view(), name='dataset_search'),
    path('api/dataset/download/', views.DatasetFileDownload.as_view(), name='dataset_download_file'),

    path('api/portlet/image/', views.ImagePortlet.as_view(), name='image_portlet'),
    path('api/portlet/score/', views.ScorePortlet.as_view(), name='score_portlet'),
    path('api/portlet/recommendation/', views.RecommendationPortlet.as_view(), name='recommendation_portlet'),
    path('api/portlet/recommendation-summary/', views.RecommendationSummaryPortlet.as_view(), name='recommendation_summary_portlet'),
    path('api/portlet/threshold/', views.ThresholdFormPortlet.as_view(), name='threshold_portlet'),
    path('api/portlet/injection/<int:dataset_id>/', views.InjectionFormPortlet.as_view(), name='injection_form_portlet'),

    path('api/threshold-update', views.DatasetThresholdUpdateJson.as_view(), name='threshold_update_json'),
    path('api/image/cnf/', views.CnfImage.as_view(), name='cnf_image'),
    path('api/image/thresholds-scores/', views.ThresholdsScoresImage.as_view(), name='thresholds_scores_image'),

    path('api/locations/<int:dataset_id>/', views.DatasetLocationsJson.as_view(), name='dataset_locations'),
]

urlpatterns = apipatterns + [

    path('account/datasets/upload/', views.AccountUploadDataset.as_view(), name='account_datasets_upload'),
    path('account/training-datasets/upload/', views.AccountUploadTrainingDataset.as_view(), name='account_training_datasets_upload'),

    path('display/real-world/', views.DisplayRealWorldDatasets.as_view(), name='display_real_world_datasets'),
    path('display/real-world/<int:dataset_id>/', views.DisplayRealWorldDataset.as_view(), name='display_real_world_dataset'),
    path('display/real-world/<int:dataset_id>/<int:training_dataset_id>/', views.DisplayRealWorldTrainingDataset.as_view(), name='display_real_world_training_dataset'),
    path('display/synthetic/', views.DisplaySyntheticDatasets.as_view(), name='display_synthetic_datasets'),
    path('display/synthetic/<int:dataset_id>/', views.DisplaySyntheticDataset.as_view(), name='display_synthetic_dataset'),
    path('display/synthetic/<int:dataset_id>/<int:training_dataset_id>/', views.DisplaySyntheticTrainingDataset.as_view(), name='display_synthetic_training_dataset'),

    path('detection/real-world/', views.DetectionRealWorldDatasets.as_view(), name='detection_real_world_datasets'),
    path('detection/real-world/<int:dataset_id>/', views.DetectionRealWorldDataset.as_view(), name='detection_real_world_dataset'),
    path('detection/synthetic/', views.DetectionSyntheticDatasets.as_view(), name='detection_synthetic_datasets'),
    path('detection/synthetic/<int:dataset_id>/', views.DetectionSyntheticDataset.as_view(), name='detection_synthetic_dataset'),

    path('recommendation/real-world/', views.RecommendationRealWorldDatasets.as_view(), name='recommendation_real_world_datasets'),
    path('recommendation/real-world/<int:dataset_id>/', views.RecommendationRealWorldDataset.as_view(), name='recommendation_real_world_dataset'),
    path('recommendation/synthetic/', views.RecommendationSyntheticDatasets.as_view(), name='recommendation_synthetic_datasets'),
    path('recommendation/synthetic/<int:dataset_id>/', views.RecommendationSyntheticDataset.as_view(), name='recommendation_synthetic_dataset'),

    path('account/application-setting/', views.ApplicationSetting.as_view(), name='application_setting'),
    path('account/datasets/', views.account_datasets, name='account_datasets'),
    path('account/datasets/<int:dataset_id>/edit/', views.AccountDatasetEdit.as_view(), name='account_dataset_edit'),
    path('account/training-datasets/<int:dataset_id>/edit/', views.AccountTrainingDatasetEdit.as_view(), name='account_training_dataset_edit'),
    path('account/training-datasets/', views.account_training_datasets, name='account_training_datasets'),
    path('account/user/update', views.AccountUserUpdate.as_view(), name='account_user_update'),
    path('account/pwd/update', views.AccountPasswordUpdate.as_view(), name='account_pwd_update'),
    path('account/delete', views.AccountDelete.as_view(), name='account_delete'),
    path('account/', views.account, name='account'),


    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

vadetisweb/models/user_models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models

from vadetisweb.parameters import *


class UserSetting(models.Model):
    """
    The user settings for the application.
    """

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    color_outliers = models.CharField('Color outliers', max_length=7, null=False, default=DEFAULT_COLOR_OUTLIERS,
                                      help_text='Default: #C30000, the RGB color used to mark outliers',
                                      validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    color_true_positive = models.CharField('Color for True Positives', max_length=7, null=False, default=DEFAULT_COLOR_TRUE_POSITIVES,
                                           help_text='Default: #008800, the RGB color used to mark true positives',
                                           validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    color_false_positive = models.CharField('Color for False Positives', max_length=7, null=False, default=DEFAULT_COLOR_FALSE_POSITIVES,
                                            help_text='Default: #FF0000, the RGB color used to mark false positives',
                                            validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    color_false_negative = models.CharField('Color for False Negatives', max_length=7, null=False, default=DEFAULT_COLOR_FALSE_NEGATIVES,
                                            help_text='Default: #0000FF, the RGB color used to mark false negatives',
                                            validators=[RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])

    def __str__(self):
        if self.user is not None:
            return self.user.username
        else:
            return 'Settings'

vadetisweb/forms/account_forms.py
from allauth.account import app_settings
from allauth.account.forms import get_adapter as get_account_adapter, SetPasswordForm, filter_users_by_email
from allauth.account.models import EmailAddress
from django.forms import ModelForm, ValidationError

from vadetisweb.models import User


#########################################################
# Account Forms
#########################################################

class AccountUserForm(ModelForm):
    """
    The form for the user basic config
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(AccountUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class' : 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        setattr(self, '__original_email', self.instance.email)

    def valid_email(self):
        value = self.instance.email
        value = get_account_adapter().clean_email(value)
        errors = {
            "different_account": "This e-mail address is already associated with another account.",
        }
        users = filter_users_by_email(value)
        on_diff_account = [u for u in users if u.pk != self.user.pk]

        if on_diff_account and app_settings.UNIQUE_EMAIL:
            raise ValidationError(errors["different_account"])
        return value

    def save(self, commit=True):
        instance = super(AccountUserForm, self).save(commit=False)

        email_address = EmailAddress.objects.get(email__iexact=getattr(self, '__original_email'), user=self.instance)
        if email_address is not None:
            email_address.email = self.cleaned_data['email']
            email_address.save()
        else:
            raise ValidationError('Something went wrong, could not set email address')
        if commit:
            instance.save()
        return instance


class AccountSetPasswordForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(AccountSetPasswordForm, self).__init__(*args, **kwargs)
        for field in ('password1', 'password2'):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def save(self):
        # Ensure you call the parent classes save
        # .save() does not return anything
        super(AccountSetPasswordForm, self).save()

vadetisweb/views.py
from django.shortcuts import render


def index(request):

    return render(request, 'vadetisweb/index.html',)

vadetisweb/views/base_views.py
from django.shortcuts import render

def index(request):
    return render(request, 'vadetisweb/index.html',)

def about(request):
    return render(request, 'vadetisweb/about.html')

def faq(request):
    return render(request, 'vadetisweb/faq.html')

vadetisweb/templates/vadetisweb/parts/header/actions.html
{% load static %}
<div class="kt-header__topbar-item kt-header__topbar-item--user">
    <div class="kt-header__topbar-wrapper" data-offset="10px,0px">
        <a href="{% url 'vadetisweb:application_setting' %}"><span class="kt-header__topbar-icon" data-toggle="kt-tooltip" data-placement="bottom" data-original-title="Settings"><i class="mdi mdi-settings-outline mdi-24px"></i></span></a>
    </div>
</div>

vadetisweb/templates/vadetisweb/parts/header/login_block.html
{% load static %}
{% if not user.is_authenticated %}
<div class="kt-header__topbar-item kt-header__topbar-item--user">
    <div class="kt-header__topbar-wrapper" data-offset="10px,0px">
        <a href="{% url 'account_login' %}"><span class="kt-header__topbar-icon pr-2 pl-2"  data-toggle="kt-tooltip" data-placement="bottom" data-original-title="Login"><i class="mdi mdi-login mdi-24px"></i></span></a>
    </div>
</div>
{% endif %}

vadetisweb/templates/vadetisweb/parts/header/search.html
{% load static %}
<div class="kt-header__topbar-item kt-header__topbar-item--search dropdown" id="kt_quick_search_toggle">
    <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,0px">
        <span class="kt-header__topbar-icon"  data-toggle="kt-tooltip" data-placement="bottom" data-original-title="Search Datasets"><i class="mdi mdi-magnify mdi-24px"></i></span>
    </div>
    <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-lg">
        <div class="kt-quick-search kt-quick-search--inline" id="kt_quick_search_inline">
            <form method="get" class="kt-quick-search__form">
                <div class="input-group">
                    <div class="input-group-prepend"><span class="input-group-text"><i class="mdi mdi-magnify mdi-24px"></i></span></div>
                    <input type="text" class="form-control kt-quick-search__input" placeholder="Search...">
                    <div class="input-group-append"><span class="input-group-text"><i class="la la-close kt-quick-search__close"></i></span></div>
                </div>
            </form>
            <div class="kt-quick-search__wrapper kt-scroll" data-scroll="true" data-height="300" data-mobile-height="200">
            </div>
        </div>
    </div>
</div>

vadetisweb/templates/vadetisweb/parts/header/user.html
{% load static %}
<div class="kt-header__topbar-item kt-header__topbar-item--user">

    {% if user.is_authenticated %}
        <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,0px">
            <span class="kt-header__topbar-username kt-visible-desktop">{{ user.username }}</span>
            <span class="kt-header__topbar-icon"><i class="mdi mdi-account mdi-24px"></i></span>

            <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
            <span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold kt-hidden">S</span>
        </div>
    {% else %}
        <div class="kt-header__topbar-wrapper" data-offset="10px,0px">
            <a href="{% url 'account_login' %}"><span class="kt-header__topbar-icon pr-2 pl-2"><span class="kt-visible-desktop">Login</span> <i class="mdi mdi-login mdi-24px"></i></span></a>
        </div>
    {% endif %}

    <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-xl">
        <!--begin: User Nav Main -->
        <div class="kt-user-card kt-user-card--skin-light kt-notification-item-padding-x">
            <div class="kt-user-card__name">
                {{ user.username }}
            </div>
            <div class="kt-user-card__badge">
                <span class="btn btn-label-primary btn-sm btn-bold btn-font-md">23 messages</span>
            </div>
        </div>
        <!--end: User Nav Main -->
        <!--begin: User Navigation -->
        <div class="kt-notification">
            <a href="{% url 'vadetisweb:account' %}" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="mdi mdi-account-outline mdi-24px kt-font-success"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                        Profile
                    </div>
                    <div class="kt-notification__item-time">
                        Account settings and more
                    </div>
                </div>
            </a>
            <a href="#" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="mdi mdi-bell-outline mdi-24px kt-font-warning"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                        Notifications
                    </div>
                    <div class="kt-notification__item-time">
                        Inbox and tasks
                    </div>
                </div>
            </a>
            <a href="#" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="mdi mdi-timeline-clock-outline mdi-24px kt-font-brand"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                        Tasks
                    </div>
                    <div class="kt-notification__item-time">
                        Latest tasks
                    </div>
                </div>
            </a>
            <a href="#" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="mdi mdi-chart-timeline-variant mdi-24px kt-font-brand"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                        My Datasets
                    </div>
                    <div class="kt-notification__item-time">
                        Manage own datasets
                    </div>
                </div>
            </a>
            <div class="kt-notification__custom kt-space-between">
                <a href="{% url 'account_logout' %}" class="btn btn-label btn-label-brand btn-sm btn-bold">Sign Out</a>
            </div>
        </div>
        <!--end: User Navigation -->
    </div>
</div>

vadetisweb/templates/vadetisweb/parts/header/user_navigation.html
{% load static %}
<div class="kt-header__topbar-item kt-header__topbar-item--user">
    <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,0px">
        <span class="kt-header__topbar-icon" data-container="body" data-toggle="kt-tooltip" data-placement="bottom" data-original-title="User Menu"><i class="mdi mdi-account mdi-24px"></i></span>
    </div>

    <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-xl">
        {% if user.is_authenticated %}
        <!--begin: User Nav Main -->
        <div class="kt-user-card kt-user-card--skin-light kt-notification-item-padding-x">
            <div class="kt-user-card__name">
                {{ user.username }}
            </div>
            <div>
            {% if user.first_name and user.last_name %}
                <span class="kt-font-primary">
                    {{ user.first_name }} {{ user.last_name }}
                </span><br/>
            {% endif %}
                <span class="kt-font-primary font-italic">
                    {% if user.is_superuser %}Administrator{% else %}Regular User{% endif %}
                </span>
            </div>
        </div>
        <!--end: User Nav Main -->
        {% endif %}
        <!--begin: User Navigation -->
        <div class="kt-notification">
            <a href="{% url 'vadetisweb:account' %}" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="mdi mdi-account-outline mdi-24px kt-font-success"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                        Profile
                    </div>
                    <div class="kt-notification__item-time">
                        Settings for your account
                    </div>
                </div>
            </a>
            <a href="{% url 'vadetisweb:account_datasets' %}" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="mdi mdi-chart-timeline-variant mdi-24px kt-font-brand"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                        Datasets
                    </div>
                    <div class="kt-notification__item-time">
                        Manage your datasets
                    </div>
                </div>
            </a>
            <a href="{% url 'vadetisweb:account_training_datasets' %}" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="mdi mdi-chart-timeline-variant mdi-24px kt-font-brand"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                        Training Datasets
                    </div>
                    <div class="kt-notification__item-time">
                        Manage your training datasets
                    </div>
                </div>
            </a>
            {% if user.is_authenticated %}
            <div class="kt-notification__custom kt-space-between">
                <a href="{% url 'account_logout' %}" class="btn btn-label btn-label-brand btn-sm btn-bold">Sign Out</a>
            </div>
            {% else %}
            <div class="kt-notification__custom kt-space-between">
                <a href="{% url 'account_login' %}" class="btn btn-label btn-label-brand btn-sm btn-bold">Login</a>
            </div>
            {% endif %}
        </div>
        <!--end: User Navigation -->
    </div>
</div>